# Generated by Django 5.2.11 on 2026-03-18 20:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
