# Generated by Django 5.2.11 on 2026-04-05 22:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Encuentra accesorios y dispositivos con la mejor experiencia de compra', max_length=255)),
                ('subtitulo', models.TextField(default='Accesorios gamer, celulares, consolas y computadores listos para apartar con atención presencial y soporte profesional.')),
                ('imagen_fondo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen de fondo')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner de Hero',
                'verbose_name_plural': 'Banners de Hero',
                'ordering': ['-orden', '-fecha_actualizacion'],
            },
        ),
    ]
