# Generated by Django 5.2.11 on 2026-04-06 00:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_actualizacion_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
