# Generated by Django 5.2.11 on 2026-04-06 02:24

import random

from django.db import migrations, models


def generar_codigos_unicos(apps, schema_editor):
    Apartado = apps.get_model('inventario', 'Apartado')
    usados = set(
        Apartado.objects.exclude(codigo_verificacion__isnull=True)
        .exclude(codigo_verificacion='')
        .values_list('codigo_verificacion', flat=True)
    )

    for apartado in Apartado.objects.filter(models.Q(codigo_verificacion__isnull=True) | models.Q(codigo_verificacion='')):
        codigo = f"{random.randint(0, 999999):06d}"
        while codigo in usados:
            codigo = f"{random.randint(0, 999999):06d}"
        apartado.codigo_verificacion = codigo
        apartado.save(update_fields=['codigo_verificacion'])
        usados.add(codigo)


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_usuario_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartado',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.RunPython(generar_codigos_unicos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='apartado',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
