# Generated by Django 5.2.11 on 2026-04-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_apartado_codigo_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepta_politicas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aceptacion_politicas',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartado',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
