# Generated by Django 5.2.11 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_usuario_acepta_politicas_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apartado',
            index=models.Index(fields=['estado', 'fecha_expiracion'], name='inventario_a_estado_fec_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='apartado',
            index=models.Index(fields=['estado', 'fecha_apartado'], name='inventario_a_estado_fec_ap_idx'),
        ),
        migrations.AddIndex(
            model_name='apartado',
            index=models.Index(fields=['usuario', 'fecha_apartado'], name='inventario_a_usuario_fec_ap_idx'),
        ),
    ]
