# Generated by Django 5.2.11 on 2026-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0009_apartado_query_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apartado",
            new_name="inventario__estado_e02756_idx",
            old_name="inventario_a_estado_fec_exp_idx",
        ),
        migrations.RenameIndex(
            model_name="apartado",
            new_name="inventario__estado_fc5721_idx",
            old_name="inventario_a_estado_fec_ap_idx",
        ),
        migrations.RenameIndex(
            model_name="apartado",
            new_name="inventario__usuario_5e7c24_idx",
            old_name="inventario_a_usuario_fec_ap_idx",
        ),
        migrations.AlterField(
            model_name="apartado",
            name="fecha_apartado",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
