services:
  - type: web
    name: servicio_tecnico
    runtime: python
    pythonVersion: 3.11
    buildCommand: chmod +x build.sh ; ./build.sh
    startCommand: gunicorn servicio_tecnico.wsgi:application --bind 0.0.0.0:$PORT

