services:
  - type: web
    name: servicio_tecnico
    runtime: python
    pythonVersion: 3.11
    buildCommand: chmod +x build.sh ; ./build.sh
    startCommand: gunicorn servicio_tecnico.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 120 --access-logfile - --error-logfile - --log-level info
    healthCheckPath: /healthz/

